### ISSUE TITLE
Provide Releases

### ISSUE THREAD

**Issue by Bluscream** [hyc/a9serv#1]
Please provide precompiled releases for the most common platforms so people dont have to install the whole toolchain everywhere

- aarch64: [pppp_c.zip](https://github.com/user-attachments/files/16770333/pppp_c.zip)

**Comment by hyc** [comment]
No. I only provide source code.

**Comment by Bluscream** [comment]
Why? Do you not want non-devs to use your software?

**Comment by SnoopyTools** [comment]
[A9camPPPP.zip](https://github.com/user-attachments/files/18286054/A9camPPPP.zip)

Windows (cygwin) exe
